import { AIModel } from "@/types/model";

export const AI_MODELS: AIModel[] = [
  // --- REASONING & FRONTIER LABS ---
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1",
    lab: "DeepSeek",
    modality: "reasoning",
    accessType: "open_weights",
    releaseDate: "January 2025",
    parameters: "671B MoE (37B active per token)",
    contextWindow: "128,000 tokens",
    license: "MIT",
    tagline: "Open-weights reasoning model trained via large-scale reinforcement learning without supervised cold start.",
    description: "DeepSeek-R1 introduces autonomous reasoning behaviors through pure reinforcement learning (DeepSeek-R1-Zero) followed by multi-stage refinement. It achieves competitive mathematical, coding, and logical reasoning benchmarks comparable to proprietary closed-source reasoning systems while providing full model weights under an MIT license.",
    strengths: ["Mathematical Proofs", "Algorithmic Code", "Transparent Chain-of-Thought", "MIT Licensed Weights"],
    architecture: "Mixture-of-Experts (MoE) with Multi-head Latent Attention (MLA) and DeepSeekMoE sparsity",
    officialUrl: "https://github.com/deepseek-ai/DeepSeek-R1",
    huggingFaceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1",
    apiDocUrl: "https://platform.deepseek.com/api-docs/",
    featured: true,
  },
  {
    id: "openai-o1",
    name: "OpenAI o1",
    lab: "OpenAI",
    modality: "reasoning",
    accessType: "commercial_api",
    releaseDate: "December 2024",
    parameters: "Undisclosed",
    contextWindow: "200,000 tokens (up to 100k completion)",
    license: "Proprietary Commercial API",
    tagline: "Frontier reasoning model designed to spend deliberate inference compute before answering complex queries.",
    description: "OpenAI o1 utilizes reinforcement learning during pre-training and test-time compute to generate private internal chains of thought. It specializes in competitive programming, physics, PhD-level biology, and multi-step theorem verification.",
    strengths: ["Competitive Programming", "Scientific Reasoning", "PhD-level STEM", "Inference-time Compute Scaling"],
    architecture: "Autoregressive Transformer with internal reasoning trace generation",
    officialUrl: "https://openai.com/o1/",
    apiDocUrl: "https://platform.openai.com/docs/guides/reasoning",
    featured: true,
  },
  {
    id: "openai-o3-mini",
    name: "OpenAI o3-mini",
    lab: "OpenAI",
    modality: "reasoning",
    accessType: "commercial_api",
    releaseDate: "January 2025",
    parameters: "Undisclosed (Compact)",
    contextWindow: "200,000 tokens",
    license: "Proprietary Commercial API",
    tagline: "High-speed, cost-efficient reasoning model with adjustable reasoning effort levels.",
    description: "Engineered specifically for STEM disciplines and technical coding workflows, o3-mini offers controllable reasoning effort (low, medium, high) allowing developers to balance latency, cost, and analytical depth for production software environments.",
    strengths: ["Adjustable Reasoning Effort", "Fast Latency", "Competitive Math", "Tool & Function Calling"],
    architecture: "Compact Autoregressive Transformer with Test-Time Compute",
    officialUrl: "https://openai.com/index/openai-o3-mini/",
    apiDocUrl: "https://platform.openai.com/docs/models#o3-mini",
    featured: false,
  },
  {
    id: "gemini-2-0-flash",
    name: "Gemini 2.0 Flash",
    lab: "Google DeepMind",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "December 2024",
    parameters: "Undisclosed",
    contextWindow: "1,048,576 tokens",
    license: "Proprietary Commercial API / Google AI Studio",
    tagline: "Ultra-fast multimodal model built for real-time streaming, multimodal tool use, and agentic workflows.",
    description: "Gemini 2.0 Flash is natively multimodal from inception across text, high-resolution audio, vision, and video. It delivers sub-second time-to-first-token latency, native bidirectional audio streaming, and seamless integration with external search grounding and code execution.",
    strengths: ["Native Audio/Vision Multimodality", "Sub-second Latency", "1M Context Window", "Multimodal Live API"],
    architecture: "Natively Multimodal Transformer",
    officialUrl: "https://deepmind.google/technologies/gemini/flash/",
    apiDocUrl: "https://ai.google.dev/gemini-api/docs/models/gemini-v2",
    featured: true,
  },
  {
    id: "gemini-2-0-pro-exp",
    name: "Gemini 2.0 Pro Experimental",
    lab: "Google DeepMind",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "February 2025",
    parameters: "Undisclosed",
    contextWindow: "2,097,152 tokens",
    license: "Proprietary Commercial API / Google AI Studio",
    tagline: "Google's frontier model for complex coding, multi-step problem solving, and 2M token context retrieval.",
    description: "Gemini 2.0 Pro Experimental achieves state-of-the-art results across code benchmarks and complex data analysis, offering 2 million tokens of context window capable of ingesting massive codebases and multi-hour video archives with high needle-in-a-haystack recall.",
    strengths: ["2M Token Context", "Complex Software Engineering", "Large Codebase Ingestion", "High-Fidelity Reasoning"],
    architecture: "Frontier Multimodal Mixture Transformer",
    officialUrl: "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/",
    apiDocUrl: "https://ai.google.dev/gemini-api/docs/models/gemini-v2",
    featured: true,
  },
  {
    id: "gemini-1-5-pro",
    name: "Gemini 1.5 Pro",
    lab: "Google DeepMind",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "May 2024",
    parameters: "Undisclosed Sparse MoE",
    contextWindow: "2,000,000 tokens",
    license: "Proprietary Commercial API",
    tagline: "Pioneering 2M token long-context multimodal model for enterprise document and video analysis.",
    description: "Gemini 1.5 Pro broke context window barriers with its 2-million-token capacity and Sparse Mixture-of-Experts architecture. It processes an hour of video, eleven hours of audio, or over 700,000 words in a single query with near-perfect retrieval.",
    strengths: ["2M Token Long Context", "Document Cross-Referencing", "Sparse MoE Efficiency", "Audio & Video Comprehension"],
    architecture: "Sparse Mixture-of-Experts (MoE) Transformer",
    officialUrl: "https://deepmind.google/technologies/gemini/pro/",
    apiDocUrl: "https://ai.google.dev/gemini-api/docs/models/gemini",
    featured: false,
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    lab: "Anthropic",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "October 2024 (Upgraded)",
    parameters: "Undisclosed",
    contextWindow: "200,000 tokens",
    license: "Proprietary Commercial API",
    tagline: "Industry benchmark leader in software engineering, nuanced writing, and Computer Use automation.",
    description: "Claude 3.5 Sonnet operates at twice the speed of Claude 3 Opus while outperforming top models on graduate-level reasoning, undergraduate-level knowledge, and software coding benchmarks. It pioneered the Computer Use API for direct OS GUI interaction.",
    strengths: ["Software Engineering (SWE-bench)", "Computer Use & OS Automation", "Nuanced Prose & Tone", "Visual Chart & Diagram Analysis"],
    architecture: "Autoregressive Multimodal Transformer",
    officialUrl: "https://www.anthropic.com/news/claude-3-5-sonnet",
    apiDocUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    featured: true,
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    lab: "Anthropic",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "November 2024",
    parameters: "Undisclosed (Compact)",
    contextWindow: "200,000 tokens",
    license: "Proprietary Commercial API",
    tagline: "High-velocity, compact intelligence with coding performance exceeding previous generation frontier models.",
    description: "Claude 3.5 Haiku is Anthropic's fastest model. Designed for high-volume enterprise tasks, user-facing chat, and agentic sub-tasks, it matches or surpasses the original Claude 3 Opus on multiple engineering benchmarks at fraction of the latency.",
    strengths: ["Ultra-low Latency", "Cost-effective Code Generation", "JSON Structured Output", "Subagent Coordination"],
    architecture: "Compact Autoregressive Transformer",
    officialUrl: "https://www.anthropic.com/news/claude-3-5-haiku",
    apiDocUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    featured: false,
  },
  {
    id: "gpt-4o",
    name: "GPT-4o (Omni)",
    lab: "OpenAI",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "May 2024",
    parameters: "Undisclosed",
    contextWindow: "128,000 tokens",
    license: "Proprietary Commercial API",
    tagline: "End-to-end multimodal foundation model for real-time speech, vision, and text interaction.",
    description: "GPT-4o trains a single neural network end-to-end across text, vision, and audio, preserving emotional inflections, background acoustics, and conversational interruptions that were lost in cascaded voice pipelines.",
    strengths: ["Real-time Voice Dialog", "Image Understanding", "Multilingual Translation", "Fast Token Generation"],
    architecture: "End-to-end Multimodal Transformer",
    officialUrl: "https://openai.com/index/hello-gpt-4o/",
    apiDocUrl: "https://platform.openai.com/docs/models#gpt-4o",
    featured: false,
  },
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B Instruct",
    lab: "Meta AI",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "December 2024",
    parameters: "70.6 Billion Dense",
    contextWindow: "128,000 tokens",
    license: "Llama 3.3 Community License",
    tagline: "State-of-the-art 70B open model matching previous 405B capabilities on industry benchmarks.",
    description: "Meta's Llama 3.3 70B incorporates post-training advancements, knowledge distillation, and online DPO to deliver industry-leading performance in a dense 70B footprint capable of running on a single modern GPU server node.",
    strengths: ["Open Weights for Enterprise", "Matches Llama 3.1 405B on Core Benchmarks", "Tool Calling & Agents", "Quantization Friendly"],
    architecture: "Dense Auto-regressive Transformer with Grouped-Query Attention (GQA)",
    officialUrl: "https://ai.meta.com/blog/meta-llama-3-3/",
    huggingFaceUrl: "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
    featured: true,
  },
  {
    id: "llama-3-1-405b",
    name: "Llama 3.1 405B",
    lab: "Meta AI",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "July 2024",
    parameters: "405 Billion Dense",
    contextWindow: "128,000 tokens",
    license: "Llama 3.1 Community License",
    tagline: "The world's largest open-weights foundational language model trained on over 15 trillion tokens.",
    description: "Trained on over 16,000 H100 GPUs, Llama 3.1 405B represents a milestone for open science, providing a premier open baseline for synthetic data generation, model distillation, and high-complexity reasoning.",
    strengths: ["Distillation Teacher Model", "Massive World Knowledge", "Synthetic Data Generation", "Open Architecture Research"],
    architecture: "405B Dense Auto-regressive Transformer with GQA",
    officialUrl: "https://ai.meta.com/blog/meta-llama-3-1/",
    huggingFaceUrl: "https://huggingface.co/meta-llama/Meta-Llama-3.1-405B",
    featured: false,
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek-V3",
    lab: "DeepSeek",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "December 2024",
    parameters: "671B MoE (37B active)",
    contextWindow: "128,000 tokens",
    license: "MIT",
    tagline: "Frontier 671B MoE base model trained for under $6M compute cost using FP8 mixed precision.",
    description: "DeepSeek-V3 uses Multi-head Latent Attention (MLA) to compress KV caches by 93% and DeepSeekMoE auxiliary-loss-free load balancing. It established unprecedented training cost efficiency while competing at the highest tier of open foundation models.",
    strengths: ["Ultra-low KV-Cache Footprint", "Training Cost Breakthrough", "MIT License", "High Throughput Inference"],
    architecture: "Mixture-of-Experts with Multi-head Latent Attention (MLA) and Multi-Token Prediction (MTP)",
    officialUrl: "https://github.com/deepseek-ai/DeepSeek-V3",
    huggingFaceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V3",
    apiDocUrl: "https://platform.deepseek.com/",
    featured: true,
  },
  {
    id: "qwen-2-5-72b",
    name: "Qwen 2.5 72B Instruct",
    lab: "Alibaba Cloud",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "September 2024",
    parameters: "72.7 Billion Dense",
    contextWindow: "128,000 tokens (up to 8k output)",
    license: "Apache 2.0",
    tagline: "Leading open-source multilingual model excelling in coding, math, and structured data extraction.",
    description: "Alibaba's flagship open-weights model trained on 18 trillion tokens across 29 languages. Qwen 2.5 72B demonstrates exceptional performance in mathematical problem solving, schema parsing, and multilingual instruction following.",
    strengths: ["Apache 2.0 Permissive License", "Superior Multilingual Performance", "Structured JSON & Table Extraction", "Long-Text Comprehension"],
    architecture: "Dense Transformer with SwiGLU, RoPE, and GQA",
    officialUrl: "https://qwenlm.github.io/blog/qwen2.5/",
    huggingFaceUrl: "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct",
    featured: false,
  },
  {
    id: "mistral-large-2",
    name: "Mistral Large 2 (2407)",
    lab: "Mistral AI",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "July 2024",
    parameters: "123 Billion Dense",
    contextWindow: "128,000 tokens",
    license: "Mistral Research License / Commercial API",
    tagline: "European frontier flagship optimized for multi-lingual reasoning, coding, and minimal hallucinations.",
    description: "Mistral Large 2 delivers enterprise-grade code generation, mathematical reasoning, and native fluency in French, German, Spanish, Italian, and 80+ coding languages, designed with strict guardrails against false confidence.",
    strengths: ["Native European Multilingualism", "Extensive Function Calling", "Precise Code Generation", "On-Premise Deployment"],
    architecture: "123B Dense Transformer with 128k context support",
    officialUrl: "https://mistral.ai/news/mistral-large-2407/",
    huggingFaceUrl: "https://huggingface.co/mistralai/Mistral-Large-Instruct-2407",
    apiDocUrl: "https://docs.mistral.ai/",
    featured: false,
  },
  {
    id: "grok-2",
    name: "Grok 2",
    lab: "xAI",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "August 2024",
    parameters: "Undisclosed",
    contextWindow: "128,000 tokens",
    license: "Proprietary Commercial API",
    tagline: "Frontier multimodal model integrated with real-time news retrieval from the X platform.",
    description: "Developed by xAI, Grok 2 features advanced vision comprehension, real-time social knowledge synthesis, and conversational agility, paired with FLUX image generation capabilities on the X platform.",
    strengths: ["Real-Time Event Synthesis", "Integrated Image Generation", "Visual Document Analysis", "Direct Platform Grounding"],
    architecture: "Frontier Multimodal Transformer",
    officialUrl: "https://x.ai/blog/grok-2",
    apiDocUrl: "https://docs.x.ai/",
    featured: false,
  },

  // --- CODE & AUTONOMOUS AGENTS ---
  {
    id: "qwen-2-5-coder-32b",
    name: "Qwen 2.5 Coder 32B Instruct",
    lab: "Alibaba Cloud",
    modality: "code",
    accessType: "open_weights",
    releaseDate: "November 2024",
    parameters: "32.5 Billion Dense",
    contextWindow: "128,000 tokens",
    license: "Apache 2.0",
    tagline: "The premier open-source coding model rivaling proprietary models like GPT-4o in software engineering.",
    description: "Trained on 5.5 trillion code tokens, Qwen 2.5 Coder 32B sets a record for open-source programming capabilities. It serves as an ideal local engine for IDE assistants, repository-scale refactoring, and multi-file debugging.",
    strengths: ["SWE-bench Verified Leader", "Apache 2.0 Open License", "Local GPU Deployable (VRAM 24GB+)", "40+ Programming Languages"],
    architecture: "Dense Transformer optimized for code syntax and AST parsing",
    officialUrl: "https://qwenlm.github.io/blog/qwen2.5-coder-family/",
    huggingFaceUrl: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct",
    featured: true,
  },
  {
    id: "codestral-2501",
    name: "Codestral 2501",
    lab: "Mistral AI",
    modality: "code",
    accessType: "open_weights",
    releaseDate: "January 2025",
    parameters: "22 Billion Dense",
    contextWindow: "256,000 tokens",
    license: "Mistral Non-Production License / Commercial API",
    tagline: "Fill-in-the-middle code model with 256k context tailored for latency-sensitive developer tools.",
    description: "Codestral is specifically tuned for fill-in-the-middle (FIM) code completion, test generation, and documentation. Its expanded 256k context allows it to ingest broad codebase contexts inside VS Code and JetBrains IDE extensions.",
    strengths: ["Fill-In-The-Middle (FIM)", "256k Context Window", "Sub-100ms Token Generation", "IDE Integration"],
    architecture: "22B Dense Transformer with FIM objective",
    officialUrl: "https://mistral.ai/news/codestral-2501/",
    huggingFaceUrl: "https://huggingface.co/mistralai/Codestral-22B-v0.1",
    apiDocUrl: "https://docs.mistral.ai/capabilities/code_generation/",
    featured: false,
  },
  {
    id: "deepseek-coder-v2",
    name: "DeepSeek-Coder-V2",
    lab: "DeepSeek",
    modality: "code",
    accessType: "open_weights",
    releaseDate: "June 2024",
    parameters: "236B MoE (21B active)",
    contextWindow: "128,000 tokens",
    license: "MIT",
    tagline: "Open-source Mixture-of-Experts model supporting 338 programming languages.",
    description: "DeepSeek-Coder-V2 was the first open-source model to attain coding scores comparable to GPT-4 Turbo. It supports 338 programming languages and expands context length to 128k tokens for repo-wide code comprehension.",
    strengths: ["338 Supported Languages", "Mixture-of-Experts Efficiency", "MIT License", "Repository-wide Context"],
    architecture: "Sparse Mixture-of-Experts with Multi-head Latent Attention",
    officialUrl: "https://github.com/deepseek-ai/DeepSeek-Coder-V2",
    huggingFaceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Instruct",
    featured: false,
  },

  // --- VISION, IMAGE & VIDEO GENERATION ---
  {
    id: "flux-1-dev",
    name: "FLUX.1 [dev]",
    lab: "Black Forest Labs",
    modality: "vision_video",
    accessType: "open_weights",
    releaseDate: "August 2024",
    parameters: "12 Billion",
    contextWindow: "Text-to-Image Diffusion",
    license: "Non-Commercial FLUX.1 [dev] License",
    tagline: "State-of-the-art 12B rectified flow transformer delivering photorealistic text-to-image synthesis.",
    description: "Created by the original engineers of Stable Diffusion, FLUX.1 leverages 12 billion parameters and flow matching to produce unmatched typographic accuracy, intricate anatomical fidelity, and photorealistic lighting.",
    strengths: ["Accurate In-Image Typography", "Photorealistic Human Anatomy", "Flow Matching Latent Dynamics", "LoRA Fine-tuning Ecosystem"],
    architecture: "12B Rectified Flow Transformer (MMDiT)",
    officialUrl: "https://blackforestlabs.ai/announcing-black-forest-labs/",
    huggingFaceUrl: "https://huggingface.co/black-forest-labs/FLUX.1-dev",
    apiDocUrl: "https://docs.bfl.ml/",
    featured: true,
  },
  {
    id: "stable-diffusion-3-5-large",
    name: "Stable Diffusion 3.5 Large",
    lab: "Stability AI",
    modality: "vision_video",
    accessType: "open_weights",
    releaseDate: "October 2024",
    parameters: "8.1 Billion",
    contextWindow: "Text-to-Image Diffusion",
    license: "Stability AI Community License",
    tagline: "Multimodal Diffusion Transformer (MMDiT) with custom prompt adherence and diverse styles.",
    description: "Stability AI's flagship 8.1B parameter open model combines separate text and image weight spaces to allow deeper conceptual alignment, customizable visual styling, and high-resolution rendering without external upscalers.",
    strengths: ["Custom Style Diversity", "Open Community License", "Separated Modality Weights", "Fine-Tuning Ecosystem"],
    architecture: "Multimodal Diffusion Transformer (MMDiT)",
    officialUrl: "https://stability.ai/news/introducing-stable-diffusion-3-5",
    huggingFaceUrl: "https://huggingface.co/stabilityai/stable-diffusion-3.5-large",
    featured: false,
  },
  {
    id: "midjourney-v6-1",
    name: "Midjourney v6.1",
    lab: "Midjourney",
    modality: "vision_video",
    accessType: "commercial_api",
    releaseDate: "July 2024",
    parameters: "Undisclosed",
    contextWindow: "Proprietary Image Synthesis",
    license: "Commercial Subscription",
    tagline: "Benchmark leader for aesthetic fidelity, cinematic textures, and artistic lighting rendering.",
    description: "Midjourney v6.1 improves skin textures, 8-pixel fine details, reduced pixel artifacts, and 25% faster generation speeds, maintaining its status as the premier commercial image generator for digital creators and art directors.",
    strengths: ["Cinematic Lighting & Coherence", "Subtle Skin Textures", "Artistic Composition", "Inpainting & Outpainting"],
    architecture: "Proprietary Latent Diffusion Transformer",
    officialUrl: "https://www.midjourney.com",
    featured: false,
  },
  {
    id: "google-veo-2",
    name: "Google Veo 2",
    lab: "Google DeepMind",
    modality: "vision_video",
    accessType: "commercial_api",
    releaseDate: "December 2024",
    parameters: "Undisclosed",
    contextWindow: "High-Definition Video Generation",
    license: "Google Cloud / VideoFX API",
    tagline: "Google's most capable video generative model producing 4K-quality cinematic clips with camera control.",
    description: "Veo 2 understands cinematic terms such as timelapses, aerial tracking shots, and lens focal lengths. It produces fluid physical simulations, realistic human movement, and temporal consistency across multiple continuous seconds.",
    strengths: ["Temporal Coherence", "Cinematic Lens Controls", "Physical Simulation Accuracy", "High Resolution Output"],
    architecture: "Spatiotemporal Latent Video Diffusion Transformer",
    officialUrl: "https://deepmind.google/technologies/veo/veo-2/",
    featured: true,
  },
  {
    id: "openai-sora",
    name: "OpenAI Sora",
    lab: "OpenAI",
    modality: "vision_video",
    accessType: "commercial_api",
    releaseDate: "December 2024",
    parameters: "Undisclosed",
    contextWindow: "Video Generation Engine",
    license: "Commercial Subscription / API",
    tagline: "World-simulator diffusion model generating complex scenes with multiple characters and camera dynamics.",
    description: "Sora operates as a diffusion model over spacetime latent patches, generating video by gradually predicting clear frames from visual noise. It maintains continuous object persistence even when subjects temporarily leave the viewport.",
    strengths: ["Spatiotemporal Patches", "Object Permanence", "Multiple Camera Angles", "High Visual Realism"],
    architecture: "Diffusion Transformer over Spacetime Latent Patches",
    officialUrl: "https://openai.com/sora/",
    featured: false,
  },
  {
    id: "runway-gen-3-alpha",
    name: "Runway Gen-3 Alpha",
    lab: "Runway",
    modality: "vision_video",
    accessType: "commercial_api",
    releaseDate: "June 2024",
    parameters: "Undisclosed",
    contextWindow: "Text/Image to Video",
    license: "Commercial Subscription / API",
    tagline: "Production-grade generative video model built with precise camera motion and temporal keyframing.",
    description: "Trained jointly on videos and images, Gen-3 Alpha represents Runway's next-generation architecture for Hollywood VFX, commercial advertising, and interactive video synthesis with expressive human acting.",
    strengths: ["Camera Motion Brush", "Director Mode Controls", "Photorealistic Human Expressiveness", "Commercial VFX Integration"],
    architecture: "Latent Spatiotemporal Video Transformer",
    officialUrl: "https://runwayml.com/research/introducing-gen-3-alpha",
    apiDocUrl: "https://docs.dev.runwayml.com/",
    featured: false,
  },

  // --- AUDIO, SPEECH & VOICE ---
  {
    id: "whisper-large-v3-turbo",
    name: "Whisper Large v3 Turbo",
    lab: "OpenAI",
    modality: "audio",
    accessType: "open_weights",
    releaseDate: "October 2024",
    parameters: "809 Million",
    contextWindow: "30-second sliding audio chunks",
    license: "MIT",
    tagline: "Pruned 809M open speech transcription model running 8x faster than standard Whisper Large v3.",
    description: "Whisper Large v3 Turbo reduces decoder layers from 32 down to 4 while preserving state-of-the-art multilingual word error rates (WER), making real-time open speech-to-text inference feasible on consumer hardware.",
    strengths: ["8x Faster Inference", "MIT License", "Near-Zero Quality Degradation", "Multilingual Speech Recognition"],
    architecture: "Sequence-to-Sequence Encoder-Decoder Transformer",
    officialUrl: "https://github.com/openai/whisper",
    huggingFaceUrl: "https://huggingface.co/openai/whisper-large-v3-turbo",
    featured: true,
  },
  {
    id: "elevenlabs-multilingual-v2",
    name: "ElevenLabs Multilingual v2",
    lab: "ElevenLabs",
    modality: "audio",
    accessType: "commercial_api",
    releaseDate: "August 2023 / Updated 2024",
    parameters: "Undisclosed",
    contextWindow: "Real-time Text-to-Speech",
    license: "Commercial API",
    tagline: "Leading generative speech synthesis engine supporting 29 languages with authentic emotional nuance.",
    description: "ElevenLabs synthesizes realistic human voices with natural cadence, pauses, emotional inflections, and zero-shot voice cloning capabilities, powering conversational AI agents and audiobook productions worldwide.",
    strengths: ["29 Language Support", "Zero-Shot Voice Cloning", "Sub-150ms Latency for Voice AI", "Emotional Cadence & Modulation"],
    architecture: "Generative Audio Latent Diffusion & Acoustic Modeling",
    officialUrl: "https://elevenlabs.io",
    apiDocUrl: "https://elevenlabs.io/docs/api-reference",
    featured: false,
  },
  {
    id: "qwen-2-audio-7b",
    name: "Qwen2-Audio 7B",
    lab: "Alibaba Cloud",
    modality: "audio",
    accessType: "open_weights",
    releaseDate: "August 2024",
    parameters: "8.2 Billion",
    contextWindow: "Direct Audio Stream Input",
    license: "Apache 2.0",
    tagline: "Voice-interactive open multimodal model capable of direct audio analysis without cascaded STT.",
    description: "Qwen2-Audio can directly accept audio speech, music, or environmental sounds and carry out conversations via text, bypassing errors introduced by intermediate speech-to-text transcription layers.",
    strengths: ["Direct Audio Comprehension", "Apache 2.0 License", "Audio Event Detection", "Conversational Voice Agent Backend"],
    architecture: "Audio-Language Multimodal Transformer",
    officialUrl: "https://qwenlm.github.io/blog/qwen2-audio/",
    huggingFaceUrl: "https://huggingface.co/Qwen/Qwen2-Audio-7B-Instruct",
    featured: false,
  },

  // --- MULTIMODAL VISION-LANGUAGE FOUNDATION ---
  {
    id: "qwen-2-5-vl-72b",
    name: "Qwen 2.5-VL 72B Instruct",
    lab: "Alibaba Cloud",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "January 2025",
    parameters: "72.5 Billion",
    contextWindow: "128,000 tokens (Native Dynamic Resolution)",
    license: "Apache 2.0",
    tagline: "Leading open vision-language model with native dynamic video parsing and screen agent grounding.",
    description: "Qwen 2.5-VL parses arbitrary image resolutions and multi-hour video feeds natively. It achieves state-of-the-art results for document visual QA, OCR, phone/PC GUI bounding box coordinates, and visual math reasoning.",
    strengths: ["Screen Agent Grounding (Click Coordinates)", "Dynamic Video Timestamp Extraction", "Apache 2.0 Open License", "Document OCR & Formula Parsing"],
    architecture: "Vision-Language Transformer with NaViT dynamic patch resolution",
    officialUrl: "https://qwenlm.github.io/blog/qwen2.5-vl/",
    huggingFaceUrl: "https://huggingface.co/Qwen/Qwen2.5-VL-72B-Instruct",
    featured: true,
  },
  {
    id: "pixtral-large",
    name: "Pixtral Large (124B)",
    lab: "Mistral AI",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "November 2024",
    parameters: "124 Billion Dense",
    contextWindow: "128,000 tokens",
    license: "Mistral Research License / Commercial API",
    tagline: "Open-weights 124B multimodal model with native 1B parameter vision encoder.",
    description: "Built upon Mistral Large 2 with a custom 1B parameter vision encoder, Pixtral Large processes arbitrarily sized images and documents without resizing distortion, providing top-tier visual reasoning and chart analysis.",
    strengths: ["Native Image Aspect Ratio Handling", "Complex Chart & Diagram Analysis", "Document OCR", "128k Multi-Image Context"],
    architecture: "124B Multimodal Transformer with 1B Vision Encoder",
    officialUrl: "https://mistral.ai/news/pixtral-large/",
    huggingFaceUrl: "https://huggingface.co/mistralai/Pixtral-Large-Instruct-2411",
    apiDocUrl: "https://docs.mistral.ai/",
    featured: false,
  },
  {
    id: "gemma-2-27b",
    name: "Gemma 2 27B",
    lab: "Google DeepMind",
    modality: "multimodal",
    accessType: "open_weights",
    releaseDate: "June 2024",
    parameters: "27.2 Billion Dense",
    contextWindow: "8,192 tokens",
    license: "Gemma Terms of Use (Open Weights)",
    tagline: "Lightweight, state-of-the-art open model engineered with knowledge distillation from larger Gemini models.",
    description: "Google's Gemma 2 27B delivers competitive performance against models more than twice its size. It utilizes local-global sliding window attention and logit soft-capping for high inference efficiency on modern workstation GPUs.",
    strengths: ["Distilled from Frontier Gemini", "Runs on Single Consumer GPU", "Permissive Commercial Research", "Logit Soft-capping Stability"],
    architecture: "Dense Transformer with Alternating Local/Global Attention",
    officialUrl: "https://deepmind.google/technologies/gemma/gemma-2/",
    huggingFaceUrl: "https://huggingface.co/google/gemma-2-27b-it",
    featured: false,
  },
  {
    id: "cohere-command-r-plus",
    name: "Command R+ (08-2024)",
    lab: "Cohere",
    modality: "multimodal",
    accessType: "commercial_api",
    releaseDate: "August 2024",
    parameters: "104 Billion Dense",
    contextWindow: "128,000 tokens",
    license: "Commercial API / Non-commercial Research",
    tagline: "Enterprise foundation model purpose-built for Retrieval-Augmented Generation (RAG) and multi-step tool use.",
    description: "Command R+ specializes in verifiable enterprise workflows, producing precise citations linked to source documents to eliminate hallucination risk in regulated banking, legal, and operational environments.",
    strengths: ["Grounded In-Line Citations", "Multi-Step Tool Orchestration", "Enterprise Multilingual Support", "RAG Vector Integration"],
    architecture: "104B Dense Transformer optimized for RAG and Tool-Use",
    officialUrl: "https://cohere.com/blog/command-r-plus-august-2024",
    huggingFaceUrl: "https://huggingface.co/CohereForAI/c4ai-command-r-plus-08-2024",
    apiDocUrl: "https://docs.cohere.com/docs/command-r-plus",
    featured: false,
  }
];

export const LAB_OPTIONS = [
  "All Labs",
  "Google DeepMind",
  "OpenAI",
  "Anthropic",
  "DeepSeek",
  "Meta AI",
  "Mistral AI",
  "Alibaba Cloud",
  "Black Forest Labs",
  "Stability AI",
  "Midjourney",
  "Runway",
  "xAI",
  "Cohere",
  "ElevenLabs",
] as const;

export const MODALITY_CONFIG: Record<
  string,
  { label: string; badgeColor: string; description: string }
> = {
  reasoning: {
    label: "Reasoning & Math",
    badgeColor: "bg-purple-100 text-purple-900 dark:bg-purple-950/60 dark:text-purple-300 border-purple-200 dark:border-purple-800/50",
    description: "Extended inference thinking models scaling test-time compute for STEM, logic, and proof validation.",
  },
  multimodal: {
    label: "Language & Multimodal",
    badgeColor: "bg-blue-100 text-blue-900 dark:bg-blue-950/60 dark:text-blue-300 border-blue-200 dark:border-blue-800/50",
    description: "Versatile foundation models understanding text, high-res images, video, and documents.",
  },
  code: {
    label: "Code & Software Agents",
    badgeColor: "bg-emerald-100 text-emerald-900 dark:bg-emerald-950/60 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800/50",
    description: "Engineered for repository-scale programming, fill-in-the-middle completion, and terminal actions.",
  },
  vision_video: {
    label: "Vision, Image & Video",
    badgeColor: "bg-amber-100 text-amber-900 dark:bg-amber-950/60 dark:text-amber-300 border-amber-200 dark:border-amber-800/50",
    description: "Generative diffusion and rectified flow transformers creating visual media and cinematic clips.",
  },
  audio: {
    label: "Audio & Speech",
    badgeColor: "bg-rose-100 text-rose-900 dark:bg-rose-950/60 dark:text-rose-300 border-rose-200 dark:border-rose-800/50",
    description: "State-of-the-art automatic speech recognition (ASR) and expressive voice synthesis.",
  },
};
